### ISSUE TITLE
Signature repository

### ISSUE THREAD

**Issue by ybelMekk** [nais/salsa#37]
The ability to specify a signature repository.

from cosign doc:
```
..cosign will default to storing signatures in the same repo as the image it is signing. 
To specify a different repo for signatures, you can set the COSIGN_REPOSITORY environment variable
```
https://github.com/sigstore/cosign#specifying-registry

**Comment by ybelMekk** [comment]
if set as an environment variabel, this is done like:

```yaml
      - name: Generate provenance, upload and sign image
        # nais/salsa@v...
        uses: ./
        with:
          key: ${{ secrets.SALSA_KMS_KEY }}
          docker_pwd: ${{ secrets.GITHUB_TOKEN }}
```
